version: '2'
services:
  app:
    ports:
    - "8282:8080"
    image: boost-app:latest
  web:
    image: boost-web:latest
    ports:
    - "8181:8181"
    volumes:
    - ./web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
  db:
    image: boost-db:latest
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
